services:
  sqlite-web:
    image: coleifer/sqlite-web:0.6.4
    container_name: specmas-sqlite-web
    command: ['/data/specmas.db', '--host', '0.0.0.0', '--port', '8080']
    ports:
      - '8080:8080'
    volumes:
      - ../../prisma:/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: specmas-mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: unless-stopped
